version: '3.8'
services:
  redis:
    image: redis:7
    container_name: voosh_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: voosh_qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  redis_data:
  qdrant_storage:
